import "@/styles/globals.css";

import { type Metadata } from "next";
import localFont from "next/font/local";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/theme-provider";
import { ToggleTheme } from "@/components/toggle-theme";
import { LayoutWrapper } from "@/components/LayoutWrapper";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const cmuSerif = localFont({
  src: [
    {
      path: "../fonts/cmunrm.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/cmunbx.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../fonts/cmunti.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../fonts/cmunbi.ttf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-cmu-serif",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${cmuSerif.variable}`} suppressHydrationWarning>
      <body className="bg-background text-foreground">
        <TRPCReactProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <LayoutWrapper>
              <ToggleTheme className="fixed top-4 right-4 z-20" />
              {children}
            </LayoutWrapper>
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
